version: "3"

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: noter-backend
      POSTGRES_USER: noter-backend
      POSTGRES_PASSWORD: noter-backend
      restart: always
    expose:
      - "5432"

  noter-backend:
    environment:
      DATABASE_URL: 'postgres://noter-backend:noter-backend@db:5432'
      NOTER_MEDIA_DIR: '/media'
      NOTER_DB_HOST: 'db'
    build:
      context: .
      dockerfile: Dockerfile
    image: noter-backend
    ports:
      - "3001:3001"
    volumes:
      - .:/noter-backend
    entrypoint: /noter-backend/docker-compose-entrypoint.sh
    depends_on:
      - db
